---
- name: install pip python modules
  sudo: true
  pip: name="{{ item }}"
  with_items:
    - toolz
    - lxml
    - pyzmq
    - logbook
    - cython
    - pysam
    - gffutils
    - biopython
    - pyvcf
    - ansible
    - elasticluster

- name: Does the bcbio image exist?
  shell: docker images | grep bcbio
  ignore_errors: yes
  register: bcbio

- name: import latest stable bcbio image
  sudo: true
  shell: docker import https://s3.amazonaws.com/bcbio/docker/bcbio-stable.gz jkern/bcbio-dev:stable
  when: bcbio.rc == 1

- name: is conda installed?
  stat:
    path: ~/install/bcbio-vm/anaconda/bin/conda
  register: conda

- name: download conda script
  get_url:
    url: http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    dest: ~/
    mode: 0755
  when: conda.stat.exists == False

- name: install conda
  shell: ~/Miniconda-latest-Linux-x86_64.sh -b -p ~/install/bcbio-vm/anaconda
  when: conda.stat.exists == False

- name: use conda to install bcbio-nextgen-vm
  shell: ~/install/bcbio-vm/anaconda/bin/conda install --yes -c https://conda.binstar.org/bcbio bcbio-nextgen-vm
  when: conda.stat.exists == False

- name: provide sym link in well-known location
  sudo: true
  file:
    src: /home/jkern/install/bcbio-vm/anaconda/bin/bcbio_vm.py
    dest: /usr/local/bin/bcbio_vm.py
    state: link
    mode: 0755
  when: conda.stat.exists == False
