---
- name: create dir for moint point 
  sudo: true
  file:
    dest: "{{ mount_pt }}"
    state: directory
    owner: jkern
    group: jkern

- name:  format disk if needed (gce specific)
  sudo: true
  shell: /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/sdb "{{ mount_pt }}"

- name: download SPAdes source code
  sudo: true
  get_url: 
    url: http://spades.bioinf.spbau.ru/release3.5.0/{{ spades_name }}.tar.gz
    dest: /tmp

- name: extract SPAdes 
  sudo: true
  unarchive:   
    src: /tmp/{{ spades_name }}.tar.gz
    dest: /tmp
    owner: jkern
    group: jkern
    copy: no

- name: compiling SPAdes 
  sudo: true
  shell: PREFIX="{{ spades_dir }}/{{ spades_name }}" ./spades_compile.sh
  args:
    chdir: /tmp/{{ spades_name }}

