---
- name: bootstrapping ansibles apt module - ensure debian is up to date
  sudo: true
  shell: apt-get update

- name: ansible depends on python-pip and python-apt debian package for the apt module
  sudo: true
  shell: apt-get install python-pip python-apt -y

- name: install build tools
  sudo: true
  apt: name={{ item }} update_cache=yes
  with_items:
    - emacs23-lucid
    - build-essential
    - cmake
    - unzip
    - bzip2
    - zlib1g
    - zlib1g-dev
    - libbz2-dev
    - less
    - tmux
    - git
    - vim
    - curl
    - python-matplotlib
