---
- name: bcbio prereq packages and personalize with my apps
  hosts: gridengine_master:gridengine_clients
  sudo: true
  tasks:
    - apt: name={{ item }}
      with_items:
        - emacs23-lucid
        - less
        - tmux
        - git
        - vim
        - unzip
        - bzip2
        - curl
        - libncurses5-dev
        - openjdk-7-jdk
        - ruby
        - r-base
        - littler
  tags:
    - prereq

- name: masternode mount points
  hosts: gridengine_master
  sudo: true
  tasks:
    - file: dest={{ item }} mode=755 owner=rover group=rover state=directory
      with_items:
        - /mnt/bcbio
        - /mnt/data

- name: gce - mount /mnt/bcbio
  hosts: gridengine_master
  sudo: true
  tasks:
    - shell: /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/sdb /mnt/bcbio

- name: gce - mount /mnt/data
  hosts: gridengine_master
  sudo: true
  tasks:
    - shell: /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/sdc /mnt/data

- name: masternode export bcbio
  hosts: gridengine_master
  sudo: true
  vars_files:
    - vars/os
  tasks:
    - nfsexport: path=/mnt/bcbio dest=/etc/exports clients="{{groups.gridengine_clients}}" options=rw,no_root_squash,sync
      notify: 
       - ensure nfs service is running
       - reload exports
  handlers:
    - include: common/handlers/main.yml
    - include: gridengine/handlers/main.yml

- name: bcbio compute nodes.
  hosts: gridengine_clients
  sudo: true
  vars:
    mount_pt: /mnt/bcbio
  vars_files:
    - vars/os
  tasks:
    - include: common/tasks/nfs-clients.yml nfsserver={{groups.gridengine_master[0]}} nfspath={{mount_pt}} nfsmount={{mount_pt}}
  handlers:
    - include: common/handlers/main.yml
    - include: gridengine/handlers/main.yml
