---
- name: install dockerpy  API - pip installed by common role 
  sudo: true
  pip:
    name: docker-py
  
- name: install docker and its dependencies
  sudo: true
  apt: name={{ item }}  update_cache=yes
  with_items:
    - docker.io

- name: user must be in docker group
  sudo: true
  user: name=jkern group=docker

- name: edit docker.io
  sudo: true
  lineinfile:
    dest: /etc/default/docker.io
    regexp: "^#DOCKER_OPTS"
    line: 'DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4" '
  notify:
    - restart docker

