---
- name: get test data for spades 
  hosts: all
  vars:
    spades_dir:  /mnt/data/SPAdes
  tasks:
    - name: create ecoli_mc data directory
      file: 
        path: "{{ spades_dir }}/dataset/ecoli_mc"
        state: directory
        owner: jkern
        group: jkern
      tags:
        getdata_mc

    - name: download ecoli_mc test data 
      get_url: 
        dest: "{{ spades_dir }}/dataset/ecoli_mc"
        url: "http://spades.bioinf.spbau.ru/spades_test_datasets/ecoli_mc/{{ item }}"
      with_items:
        - README
        - s_6_1.fastq.gz
        - s_6_2.fastq.gz
      tags:
        getdata_mc

    - name: create ecoli_sc data directory
      file: 
        path: "{{ spades_dir }}/dataset/ecoli_sc"
        state: directory
        owner: jkern
        group: jkern
      tags:
        getdata

    - name: download ecoli_sc test data 
      get_url: 
        dest: "{{ spades_dir }}/dataset/ecoli_sc"
        url: "http://spades.bioinf.spbau.ru/spades_test_datasets/ecoli_sc/{{ item }}"
      with_items:
        - README
        - ecoli_mda_lane1_left.fastq
        - ecoli_mda_lane1_right.fastq
      tags:
        getdata
